name: Java-workflow2

on:
  push: 
    branches:
      - main 

jobs: 
  build:
    name: my-spc
    runs-on: self-hosted  

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: build Java with maven
        run: mvn package
      - name: build and analyze
        run: |
          mvn package sonar:sonar \
          -Dsonar.projectKey=narasimhakasimkota1998-cloud_spring-petclinic \
          -Dsonar.organization=narasimhakasimkota1998-cloud \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{secrets.SONAR_TOKEN}} 