name: Java-workflow2

on:
  push: 
    branches:
      - main 

jobs: 
  build:
    name: my-spc
    runs-on: self-hosted  

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: build Java with maven
        run: mvn package
        - name: build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.organization=narasimhakasimkota1998-cloud \
          -Dsonar.projectKey=narasimhakasimkota1998-cloud_spring-petclinic